<?php
/**
 * @file
 * Support for profiles in account page.
 */

//@todo move to .info?
require_once("profile2_one_page.admin.inc");

/**
 * Implements hook_menu_alter()
 *
 * Disable profile tabs if they are marked to be shown in accounts form
 *
 * @param $items
 */
function profile2_one_page_menu_alter(&$items) {
  $types = profile2_get_types();
  foreach ($types as $type) {
    /** @var $type ProfileType */
    if (isset($type->data['use_one_page']) && $type->data['use_one_page']) {
      $items['user/%user_category/edit/' . $type->type]['access callback'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Attach selected profiles to user edit form.
 */
function profile2_one_page_form_user_profile_form_alter(&$form, &$form_state) {

  $types = profile2_get_types();

  //we take care of profiles weights
  usort($types, '_sort_profile_by_weight');

  foreach ($types as $type) {

    /** @var $type ProfileType */
    if (isset($type->data['use_one_page']) && $type->data['use_one_page']) {

      if (!isset($form_state["profiles"])) {
        $form_state["profiles"] = array();
      }

      $profile = profile2_load_by_user($form['#user'], $type->type);

      if (empty($profile)) {
        $profile = profile_create(array('type' => $type->type, 'uid' => $form['#user']->uid));
      }

      $form_state['profiles'][$profile->type] = $profile;
    }

  }

  profile2_attach_form($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Alter for user_admin_settings()
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function profile2_one_page_form_user_admin_settings_alter(&$form, &$form_state) {
  $form['profile2_one_page'] = array(
    '#type' => 'fieldset',
    '#title' => t('Profile2 one page'),
    '#weight' => 0
  );

  $form['profile2_one_page']['profile2_one_page_wrap_account'] = array(
    '#type' => 'checkbox',
    '#title' => t('Wrap account form in a fieldset.'),
    '#default_value' => variable_get('profile2_one_page_wrap_account', FALSE),
  );

  $form['profile2_one_page']['profile2_one_page_wrap_account_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Fieldset title'),
    '#default_value' => t(variable_get('profile2_one_page_wrap_account_title', "User account")),
  );

}

/**
 * Helper to sort profiles based on weight prop.
 *
 * @param ProfileType $a
 * @param ProfileType $b
 *
 * Example usage:
 * @code
 * $types = profile2_get_types();
 * usort($types, '_sort_profile_by_weight');
 * @endcode
 *
 * @return int
 */
function _sort_profile_by_weight($a, $b) {
  return $a->weight == $b->weight ? 0 : ($a->weight > $b->weight) ? 1 : -1;
}
