<?php

function profile2_field_custom_visibility_init() {
}

/**
 * Implements hook_entity_info()
 */
function profile2_field_custom_visibility_entity_info() {
  $return = array(
    'profile2fcv' => array(
      'label' => t('profile2 privacy fields'),
      'controller class' => 'EntityAPIController',
      'base table' => 'profile2_fcv',
      'entity keys' => array('id' => 'id'),
      'module' => 'profile2_field_custom_visibility',
    ),
  );
  return $return;
}

/**
 * Implements hook_menu()
 *
 * Adds 'Custom visibility' tab in every profile edition.
 */
function profile2_field_custom_visibility_menu() {

  $items = array();
  $entity_info = entity_get_info("profile2");

  foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {

    if (isset($bundle_info['admin'])) {

      // Extract access information, providing defaults.
      $access = array_intersect_key($bundle_info['admin'], drupal_map_assoc(array(
        'access callback',
        'access arguments'
      ))) + array(
        'access callback' => 'user_access',
        'access arguments' => array('administer site configuration'),
      );

      $items[$bundle_info['admin']['path'] . "/user-manage"] = array(
        'title' => 'Custom visibility',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
          'profile2_field_custom_visibility_bundle_config_form',
          $bundle_info['admin']['bundle argument']
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
      ) + $access;

    }
  }

  return $items;

}

/**
 * Callback form of $bundle_info['admin']['path'] . "/user-manage"
 * @param $form
 * @param $form_state
 * @param $bundle
 * @return array
 */
function profile2_field_custom_visibility_bundle_config_form($form, &$form_state, $bundle) {

  $bundle_name = field_extract_bundle("profile2", $bundle);
  $instances = field_info_instances("profile2", $bundle_name);

  $form += array(
    '#bundle' => $bundle,
  );

  $form['fields'] = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => t('Profile2 one page'),
    '#description' => t('Select the fields on which allows the user to choose whether to display them or not.<br /><strong>ATTENTION: if user does not explicitly mark his fields to be exposed, they will not be shown.<br />Finally ensure "Make the content of this field private." option is not checked in these fields.</strong>'),
    '#weight' => 0
  );

  foreach ($instances as $name => $instance) {

    $checked = isset($bundle->data['user_custom_visibility']) && in_array($name, $bundle->data['user_custom_visibility']);

    $form['fields'][$name] = array(
      '#type' => 'checkbox',
      '#title' => check_plain($instance['label']),
      '#default_value' => $checked,
    );

  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

/**
 * Submit callback.
 * @see profile2_field_custom_visibility_bundle_config_form()
 */
function profile2_field_custom_visibility_bundle_config_form_submit($form, &$form_state) {
  $marked = array_filter($form_state['values']['fields']);
  /** @var $bundle ProfileType */
  $bundle = & $form['#bundle'];
  $bundle->data["user_custom_visibility"] = array_keys($marked);
  $bundle->save();
}

/**
 * Implements hook_field_access()
 */
function profile2_field_custom_visibility_field_access($op, $field, $entity_type, $profile, $account) {

  if ($profile instanceof Profile && $op == "view") {

    $bundle = profile2_get_types($profile->type);

    if (isset($bundle->data['user_custom_visibility'])) {

      $delegated = $bundle->data['user_custom_visibility'];

      $fcv = entity_load("profile2fcv", FALSE, array('uid' => $profile->uid, 'type' => $profile->type));
      if (count($fcv) == 1) {

        $fcv = array_pop($fcv);

        if (in_array($field['field_name'], $delegated)) {
          return in_array($field['field_name'], $fcv->allowed);
        }
      }
    }
  }
}

/**
 * Alteramos los formularios de perfiles
 */
function profile2_field_custom_visibility_form_profile2_form_alter(&$form, &$form_state) {

  foreach ($form_state['profiles'] as $profile) {
    $name = field_extract_bundle("profile2", $profile->type);
    $bundle = profile2_get_types($name);
    $allowed_fields = isset($bundle->data['user_custom_visibility']) ? $bundle->data['user_custom_visibility'] : array();

    $fcv = entity_load("profile2fcv", FALSE, array('uid' => $profile->uid, 'type' => $profile->type));
    $fcv = array_pop($fcv);

    foreach ($allowed_fields as $allowed_field) {

      $form["profile_" . $name][$allowed_field]["expose_" . $allowed_field] = array(
        '#type' => 'checkbox',
        '#title' => t("Expose this"),
        '#default_value' => isset($fcv->allowed) && in_array($allowed_field, $fcv->allowed),
        '#prefix' => '<div class="exponer-este-field">',
        '#suffix' => '</div>',
      );
    }

  }

  $form['#submit'][] = 'profile2_field_custom_visibility_form_profile2_form_alter_submit';
}

/**
 * Form submit callback
 * @see profile2_field_custom_visibility_form_profile2_form_alter()
 */
function profile2_field_custom_visibility_form_profile2_form_alter_submit(&$form, &$form_state) {

  /** @var $controller EntityAPIController */
  $controller = entity_get_controller("profile2fcv");

  foreach ($form_state['profiles'] as $profile) {
    $name = field_extract_bundle("profile2", $profile->type);
    $allow_these = array();

    if (isset($form_state['values']["profile_" . $name])) {
      foreach ($form_state['values']["profile_" . $name] as $field_name => $field_value) {
        if (isset($field_value["expose_" . $field_name]) && $field_value["expose_" . $field_name] === 1) {
          $allow_these[] = $field_name;
        }
      }
    }

    //el type "socio" si y el uid
    //compruebo si ya tenia almacenado algun profile2fcv para este perfil-usuario
    $fcv = $controller->load(FALSE, array('uid' => $profile->uid, 'type' => $profile->type));

    if (!$fcv) {
      $fcv = $controller->create(array(
        'uid' => $profile->uid,
        'type' => $profile->type,
        'allowed' => $allow_these
      ));
      $controller->save($fcv);
    }
    else {
      $fcv = array_pop($fcv);
      $fcv->allowed = $allow_these;
      $controller->save($fcv);
    }
    //ahora guargamos la referencia del perfil y los field que el usuario haya marcado para mostrar ($allow_these)
    //para luego usa esta informacion a la hora de mostrar la info.
  }

}
